### ISSUE TITLE
Alphabetize conditions in results page

### ISSUE THREAD

**Issue by colinrsmall** [ModernVivo/mv-frontend#4]
There is currently no basis to the order of conditions (in bold) listed on the results page:

<img width="1088" alt="image" src="https://github.com/ModernVivo/mv-frontend/assets/20507041/70276837-9aa0-441a-af06-dc6732afed41">

Instead, the order of conditions in the table should be alphabetized .

**Comment by huylesitdn** [comment]
@colinrsmall it needs order by from backend api

**Comment by colinrsmall** [comment]
Gotcha. Can you make the fix in the backend?

**Comment by huylesitdn** [comment]
@colinrsmall Please check mv-backend. I just push a change

**Comment by colinrsmall** [comment]
The proposed change breaks the filter box:

```
Internal Server Error: /api/core/conditions/values/
Traceback (most recent call last):
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidColumnReference: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("value_lower") "paper_condition_value"."...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/Users/colinsmall/github/mv_backend/src/core/serializers.py", line 41, in get_values
    return ValueSerializer(query, many=True).data
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/colinsmall/opt/miniconda3/envs/modernvivo-dev/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("value_lower") "paper_condition_value"."...
                            ^
```

Please test on your end and fix.

**Comment by huylesitdn** [comment]
https://github.com/ModernVivo/mv_backend/pull/2
